import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  safelist: [
    "bg-[#0a0a0a]/95",
    "backdrop-blur-md",
    "border-b",
    "border-white/5",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#393939",
        "on-tertiary": "#2f3131",
        surface: "#131313",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-variant": "#353535",
        tertiary: "#c6c6c7",
        "primary-fixed-dim": "#c9c6c5",
        error: "#ffb4ab",
        "on-secondary-fixed-variant": "#92001c",
        "tertiary-fixed": "#e2e2e2",
        "surface-container": "#20201f",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-container": "#080a0a",
        outline: "#8e9192",
        "secondary-fixed-dim": "#ffb3b1",
        "surface-tint": "#c9c6c5",
        "on-error": "#690005",
        "on-surface-variant": "#c4c7c7",
        "on-primary-fixed-variant": "#474646",
        "surface-container-high": "#2a2a2a",
        "outline-variant": "#444748",
        "on-primary": "#313030",
        "on-secondary": "#680011",
        "on-primary-container": "#7b7979",
        "on-surface": "#e5e2e1",
        "secondary-fixed": "#ffdad8",
        "on-background": "#e5e2e1",
        "surface-container-highest": "#353535",
        "primary-fixed": "#e5e2e1",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed-variant": "#454747",
        secondary: "#ffb3b1",
        "on-secondary-fixed": "#410007",
        "on-secondary-container": "#ffb8b5",
        "surface-dim": "#131313",
        "surface-container-low": "#1c1b1b",
        "inverse-on-surface": "#313030",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#5f5e5e",
        "on-tertiary-container": "#78797a",
        "secondary-container": "#ad0224",
        "error-container": "#93000a",
        "on-primary-fixed": "#1c1b1b",
        "primary-container": "#0a0a0a",
        primary: "#c9c6c5",
        background: "#131313",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        gutter: "24px",
        "section-padding": "120px",
        "container-max": "1200px",
        unit: "8px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        handwritten: ["La Belle Aurore", "cursive"],
      },
      fontSize: {
        "display-lg": [
          "64px",
          { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "40px", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [],
} satisfies Config;
